Update deploy-angular-ec2.yml

diff --git a/.github/workflows/deploy-angular-ec2.yml b/.github/workflows/deploy-angular-ec2.yml
--- a/.github/workflows/deploy-angular-ec2.yml
+++ b/.github/workflows/deploy-angular-ec2.yml
@@ -26,8 +26,11 @@ jobs:
 
       - name: Check SSH key exists
         run: |
-          echo "${{ secrets.EC2_SSH_KEY }}" | head -1
-          echo "${{ secrets.EC2_SSH_KEY }}" | tail -1
+          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
+            echo "SSH key is missing"
+            exit 1
+          fi
+          echo "SSH key exists"
 
       - name: Copy Angular build to EC2
         uses: appleboy/scp-action@v0.1.7
@@ -36,7 +39,7 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           source: "dist/**"
-          target: "~/angular-deploy"
+          target: "/home/${{ secrets.EC2_USER }}/angular-deploy"
 
       - name: Deploy to Nginx
         uses: appleboy/ssh-action@v1.0.3
@@ -51,7 +54,7 @@ jobs:
             sudo rm -rf /usr/share/nginx/html/*
 
             echo "Copying new Angular build..."
-            sudo cp -r ~/angular-deploy/dist/*/* /usr/share/nginx/html/
+            sudo cp -r /home/${{ secrets.EC2_USER }}/angular-deploy/dist/*/browser/* /usr/share/nginx/html/
 
             echo "Restarting Nginx..."
             sudo systemctl restart nginx
